micronaut:
  application:
    name: tmgr
datasources:
  default:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driverClassName: ${JDBC_DRIVER}
jpa:
  default:
    packages-to-scan:
      - 'sh.mazurkiewicz.tmgr.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false


